name: Build UPX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: centos:latest
      options: --dns=8.8.8.8

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CentOS repo
        run: |
          echo "[baseos]" > /etc/yum.repos.d/CentOS-Base.repo
          echo "name=CentOS-\$releasever - Base" >> /etc/yum.repos.d/CentOS-Base.repo
          echo "baseurl=http://vault.centos.org/centos/8/os/\$basearch/" >> /etc/yum.repos.d/CentOS-Base.repo
          echo "enabled=1" >> /etc/yum.repos.d/CentOS-Base.repo
          echo "gpgcheck=1" >> /etc/yum.repos.d/CentOS-Base.repo
          echo "gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centos8" >> /etc/yum.repos.d/CentOS-Base.repo

      - name: Install dependencies
        run: |
          yum -y update
          yum -y groupinstall "Development Tools"
          yum -y install git

      - name: Build UPX
        run: |
          git submodule update --init --recursive
          make CXXFLAGS="-Wno-error" all

      - name: Archive binaries
        run: |
          tar -czf upx.tar.gz -C build/release .

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: upx-binaries
          path: upx.tar.gz
