name: Build UPX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: centos:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yum -y update
          yum -y groupinstall "Development Tools"
          yum -y install git

      - name: Build UPX
        run: |
          git submodule update --init --recursive
          make CXXFLAGS="-Wno-error" all

      - name: Archive binaries
        run: |
          tar -czf upx.tar.gz -C build/release .

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: upx-binaries
          path: upx.tar.gz
